require:
  - rubocop-rails
  - rubocop-rspec
inherit_mode:
  merge:
    - Exclude
AllCops:
  TargetRubyVersion: 3.0.1
  NewCops: enable
  Exclude:
    - db/**/*
    - bin/*
    - node_modules/**/*
    - .simplecov
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2
Layout/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
