version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - db
      - redis
    command:
      - puma -C config/puma.rb
    environment:
      - DB_HOST=db
      - REDIS_URL=redis://redis:6379/0
  db:
    image: postgres:13.4-alpine
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    command:
      - foremant start
  redis:
    image:  redis:6.2.5-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  pg_data:
  redis_data:
