version: '3.8'
services:
  rails:
    container_name: rails
    extends:
      file: docker-compose.base.yml
      service: base
    command: bundle exec puma -C config/puma.rb
    ports:
      - "5000:5000"
    links:
      - db
      - redis
  sidekiq:
    container_name: sidekiq
    extends:
      file: docker-compose.base.yml
      service: base
    command: bundle exec sidekiq -C config/sidekiq.yml
    links:
      - db
      - redis
  db:
    extends:
      file: docker-compose.base.yml
      service: postgres_base
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis_base
    volumes:
      - redis_data:/data
volumes:
  pg_data:
  redis_data:
