name: RSpec & Undercover
on:
  - push
  - pull_request
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      OPEN_WEATHER_API_KEY: somedisabledkey
      TWITTER_API_KEY: somedisabledkey
      TWITTER_API_SECRET: somedisabledkey
      TWITTER_ACCESS_TOKEN: somedisabledkey
      TWITTER_ACCESS_TOKEN_SECRET: somedisabledkey
      JWT_SECRET: jwtsecret
    services:
      postgres:
        image: postgres:13.4-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
      redis:
        image: redis:6.2.5-alpine
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          bundler-cache: true
      - name: Setup database
        run: |
          bin/rails db:create
          bin/rails db:schema:load
      - name: Run RSpec
        run: |
          git fetch && git pull
          bundle exec rspec
          bundle exec undercover -c origin/master
