name: RSpec

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.4-alpine
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        # tmpfs makes DB faster by using RAM
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:6.2.5-alpine
        ports:
          - 6379:6379
        options: --entrypoint redis-server
    steps:
      - uses: actions/checkout@v2
      - name: Add Ubuntu Source Repository
        uses: myci-actions/add-deb-repo@8
        with:
          repo: deb-src http://archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse
          repo-name: ubuntu-source
          keys: 379CE192D401AB61
          key-server: keyserver.ubuntu.com
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.1
      - name: Cache bundler packages
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle install
        env:
          RAILS_ENV: test
        run: |
          gem update bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Set up Database and RabbitMQ
        run: |
          bin/rails db:create
          bin/rails db:schema:load
      - name: Run RSpec tests
        run: |
          bundle exec rspec
