name: RSpec

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      OPEN_WEATHER_API_KEY: somedisabledkey
      TWITTER_API_KEY: somedisabledkey
      TWITTER_API_SECRET: somedisabledkey
      TWITTER_ACCESS_TOKEN: somedisabledkey
      TWITTER_ACCESS_TOKEN_SECRET: somedisabledkey
    services:
      postgres:
        image: postgres:13.4-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
      redis:
        image: redis:6.2.5-alpine
        ports:
          - 6379:6379
        options: --entrypoint redis-server
    steps:
      - uses: actions/checkout@v2
      - name: Add Ubuntu Source Repository
        uses: myci-actions/add-deb-repo@8
        with:
          repo: deb-src http://archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse
          repo-name: ubuntu-source
          keys: 379CE192D401AB61
          key-server: keyserver.ubuntu.com
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1
          bundler-cache: true
      - name: Set up Database
        run: |
          bin/rails db:create
          bin/rails db:schema:load
      - name: Run RSpec tests
        run: |
          bundle exec rspec
